### ISSUE TITLE
DDS Parsing failed

### ISSUE THREAD

**Issue by bilaizi** [GlebchanskyGit/SolarSystem-3D#2]
Hello and thank you for your nice project
![image](https://user-images.githubusercontent.com/11622995/232278585-0ac27a0f-8c8c-4945-a26a-81c784a163b1.png)

**Comment by bilaizi** [comment]
大文件没下载下来

**Comment by bilaizi** [comment]
<img width="960" alt="1681632894018" src="https://user-images.githubusercontent.com/11622995/232284673-cfe51821-7dc9-47fe-a0e9-79817f41fbc6.png">

**Comment by bilaizi** [comment]
<img width="723" alt="1681633063597" src="https://user-images.githubusercontent.com/11622995/232285109-83d3c26a-22c2-49c6-9bd6-bb5413a9170d.png">

**Comment by GTruf** [comment]
@bilaizi, Hi, thanks for the feedback on my project!
About the implementation in `nv_dds.cpp` file, it's not mine, it's from NVIDIA. About the `git lfs pull`: from what [I've read online](https://forum.image.sc/t/deepprofiler-example-data-download-this-repository-is-over-its-data-quota/72903/2), the problem is that without archiving the repository, it won't let the files labeled `LFS` be packaged (another way is to pay me GitHub for extra storage for large files). [Here's the solution](https://github.com/nabla-c0d3/nassl/issues/17#issuecomment-804149931).
